# Generated by Django 5.2.8 on 2025-11-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='mobile',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
