# Generated by Django 5.2.8 on 2025-11-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd_app', '0002_transaction_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='mobile',
            field=models.CharField(),
        ),
    ]
