# Generated by Django 5.2.8 on 2025-11-15 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd_app', '0003_alter_transaction_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetrievalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('no_record', 'No Record Found')], default='pending', max_length=32)),
                ('notes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ussd_app.transaction')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ussd_app.ussdsession')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
